language: node_js
node_js:
  - 13

script:
  - npm run build:prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: dist
  on:
    branch: master
